default:
  image:
    name: mcr.microsoft.com/dotnet/sdk:8.0@sha256:363f595704ae9f9be51db003e49b75f65197b0a44d39cba6f7e2d9b020458604
    entrypoint: [""]
  tags:
    - pangea-internal
  cache:
    paths:
      - "./packages/pangea-sdk/PangeaCyber.Net/obj/project.assets.json"
      - "./packages/pangea-sdk/PangeaCyber.Net/obj/*.csproj.nuget.*"
      - ".nuget"
    policy: pull-push

.sdk-base:
  before_script:
    - dotnet restore --packages .nuget
    - dotnet build --no-restore --configuration Release

.sdk-test-base:
  retry: 2
  variables:
    CLOUD: AWS

    # Set each service test environment
    SERVICE_AI_GUARD_ENV: LVE
    SERVICE_AUDIT_ENV: LVE
    SERVICE_AUTHN_ENV: LVE
    SERVICE_AUTHZ_ENV: LVE
    SERVICE_EMBARGO_ENV: LVE
    SERVICE_FILE_SCAN_ENV: LVE
    SERVICE_IP_INTEL_ENV: LVE
    SERVICE_DOMAIN_INTEL_ENV: LVE
    SERVICE_URL_INTEL_ENV: LVE
    SERVICE_FILE_INTEL_ENV: LVE
    SERVICE_USER_INTEL_ENV: LVE
    SERVICE_PROMPT_GUARD_ENV: LVE
    SERVICE_REDACT_ENV: LVE
    SERVICE_SANITIZE_ENV: LVE
    SERVICE_VAULT_ENV: LVE
    SERVICE_SHARE_ENV: LVE

  before_script:
    - echo ${ENV}
    - echo ${CLOUD}
    - echo ${TEST}

    # Update environment variables
    # Domain
    - export PANGEA_INTEGRATION_DOMAIN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_DOMAIN_${ENV}_${CLOUD})"
    # Tokens
    - export PANGEA_INTEGRATION_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_TOKEN_${ENV}_${CLOUD})"
    - export PANGEA_INTEGRATION_VAULT_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_VAULT_TOKEN_${ENV}_${CLOUD})"
    - export PANGEA_INTEGRATION_CUSTOM_SCHEMA_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_CUSTOM_SCHEMA_TOKEN_${ENV}_${CLOUD})"
    - export PANGEA_INTEGRATION_MULTI_CONFIG_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_MULTI_CONFIG_TOKEN_${ENV}_${CLOUD})"
    # Config IDs
    - export PANGEA_AUDIT_CONFIG_ID_1_${ENV}="$(eval echo \$PANGEA_AUDIT_CONFIG_ID_1_${ENV}_${CLOUD})"
    - export PANGEA_AUDIT_CONFIG_ID_2_${ENV}="$(eval echo \$PANGEA_AUDIT_CONFIG_ID_2_${ENV}_${CLOUD})"
    - export PANGEA_AUDIT_CONFIG_ID_3_${ENV}="$(eval echo \$PANGEA_AUDIT_CONFIG_ID_3_${ENV}_${CLOUD})"
    - export PANGEA_REDACT_CONFIG_ID_1_${ENV}="$(eval echo \$PANGEA_REDACT_CONFIG_ID_1_${ENV}_${CLOUD})"
    - export PANGEA_REDACT_CONFIG_ID_2_${ENV}="$(eval echo \$PANGEA_REDACT_CONFIG_ID_2_${ENV}_${CLOUD})"

    - dotnet restore --packages .nuget
    - dotnet build --no-restore --configuration Release

  parallel:
    matrix:
      - ENV: ${SERVICE_AI_GUARD_ENV}
        TEST: ITAIGuardTest
      - ENV: ${SERVICE_AUDIT_ENV}
        TEST: ITAuditTest
      - ENV: ${SERVICE_AUTHN_ENV}
        TEST: ITAuthNTest
      - ENV: ${SERVICE_AUTHZ_ENV}
        TEST: ITAuthZTest
      - ENV: ${SERVICE_EMBARGO_ENV}
        TEST: ITEmbargoTest
      - ENV: ${SERVICE_DOMAIN_INTEL_ENV}
        TEST: ITDomainIntelTest
      - ENV: ${SERVICE_IP_INTEL_ENV}
        TEST: ITIPIntelTest
      - ENV: ${SERVICE_URL_INTEL_ENV}
        TEST: ITURLIntelTest
      - ENV: ${SERVICE_USER_INTEL_ENV}
        TEST: ITUserIntelTest
      - ENV: ${SERVICE_FILE_INTEL_ENV}
        TEST: ITFileIntelTest
      - ENV: ${SERVICE_FILE_SCAN_ENV}
        TEST: ITFileScanTest
      - ENV: ${SERVICE_PROMPT_GUARD_ENV}
        TEST: ITPromptGuardTest
      - ENV: ${SERVICE_REDACT_ENV}
        TEST: ITRedactTest
      - ENV: ${SERVICE_SANITIZE_ENV}
        TEST: ITSanitizeTest
      - ENV: ${SERVICE_VAULT_ENV}
        TEST: ITVaultTest
      - ENV: ${SERVICE_SHARE_ENV}
        TEST: ITShareTest

sdk-integration-tests:
  extends: .sdk-test-base
  needs: []
  script:
    - dotnet test --no-restore --filter ${TEST}

publish:
  extends: .sdk-base
  needs: []
  script:
    - bash ../../dev/validate_tag.sh $CI_COMMIT_TAG
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - PACKAGE_VERSION=`cat VERSION`
    - dotnet pack ./packages/pangea-sdk/PangeaCyber.Net/ -c Release --no-build --nologo -o ./ -p:PackageVersion=$PACKAGE_VERSION
    - cp .secure_files/CodeSigning_CABundle.crt /usr/local/share/ca-certificates
    - update-ca-certificates
    - dotnet nuget sign ./packages/pangea-sdk/PangeaCyber.Net/bin/Release/Pangea.SDK.$PACKAGE_VERSION.nupkg --timestamper http://timestamp.sectigo.com --certificate-path .secure_files/pangea.pfx -v d
    - dotnet nuget push ./packages/pangea-sdk/PangeaCyber.Net/bin/Release/Pangea.SDK.$PACKAGE_VERSION.nupkg -s $NUGET_SOURCE -k $NUGET_API_KEY
    - rm -rf .secure_files
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - packages/pangea-sdk/PangeaCyber.Net/bin/Release/Pangea.SDK.*.nupkg
  rules:
    - if: $CI_COMMIT_TAG

include:
  - /examples/.gitlab-ci.yml
