image:
  name: mcr.microsoft.com/dotnet/sdk:6.0
  entrypoint: [""]

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - "./PangeaCyber.Net/obj/project.assets.json"
    - "./PangeaCyber.Net/obj/*.csproj.nuget.*"
    - ".nuget"
  policy: pull-push

before_script:
  - dotnet restore --packages .nuget
  - dotnet build --no-restore --configuration Release

tests:
  stage: test
  script:
    - dotnet test --no-restore

publish:
  stage: publish
  script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - PACKAGE_VERSION=`cat VERSION`
    - dotnet pack ./PangeaCyber.Net/ -c Release --no-build --nologo  -o ./ -p:PackageVersion=$PACKAGE_VERSION
    - dotnet nuget sign ./PangeaCyber.Net/bin/Release/Pangea.SDK.$PACKAGE_VERSION.nupkg --certificate-path .secure_files/nuget.bundle --timestamper http://timestamp.digicert.com
    # - dotnet nuget push ./PangeaCyber.Net/bin/Release/Pangea.SDK.$PACKAGE_VERSION.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
    - rm -rf .secure_files
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - PangeaCyber.Net/bin/Release/Pangea.SDK.$PACKAGE_VERSION.nupkg
  only:
    - tags

stages:
  - test
  - publish
