default:
  image:
    name: mcr.microsoft.com/dotnet/sdk:6.0@sha256:ba7877fb3a171ad4326caf97d8b56304fe73e6e05da0992775804805f6f75451
    entrypoint: [""]
  tags:
    - pangea-internal
  cache:
    paths:
      - "./packages/pangea-sdk/PangeaCyber.Net/obj/project.assets.json"
      - "./packages/pangea-sdk/PangeaCyber.Net/obj/*.csproj.nuget.*"
      - "./packages/pangea-sdk/.nuget"
    policy: pull-push

.sdk-base:
  before_script:
    - cd packages/pangea-sdk
    - dotnet restore --packages .nuget
    - dotnet build --no-restore --configuration Release

.sdk-test-base:
  stage: integration_tests
  retry: 2
  variables:
  # Set each service test environment
    SERVICE_AUDIT_ENV: LVE
    SERVICE_AUTHN_ENV: LVE
    SERVICE_AUTHZ_ENV: LVE
    SERVICE_EMBARGO_ENV: LVE
    SERVICE_FILE_SCAN_ENV: LVE
    SERVICE_IP_INTEL_ENV: LVE
    SERVICE_DOMAIN_INTEL_ENV: LVE
    SERVICE_URL_INTEL_ENV: LVE
    SERVICE_FILE_INTEL_ENV: LVE
    SERVICE_USER_INTEL_ENV: LVE
    SERVICE_REDACT_ENV: LVE
    SERVICE_SANITIZE_ENV: LVE
    SERVICE_VAULT_ENV: LVE
    SERVICE_SHARE_ENV: LVE

  before_script:
    - echo ${ENV}
    - echo ${CLOUD}
    - echo ${TEST}

    # Update environment variables
    # Domain
    - export PANGEA_INTEGRATION_DOMAIN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_DOMAIN_${ENV}_${CLOUD})"
    # Tokens
    - export PANGEA_INTEGRATION_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_TOKEN_${ENV}_${CLOUD})"
    - export PANGEA_INTEGRATION_VAULT_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_VAULT_TOKEN_${ENV}_${CLOUD})"
    - export PANGEA_INTEGRATION_CUSTOM_SCHEMA_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_CUSTOM_SCHEMA_TOKEN_${ENV}_${CLOUD})"
    - export PANGEA_INTEGRATION_MULTI_CONFIG_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_MULTI_CONFIG_TOKEN_${ENV}_${CLOUD})"
    # Config IDs
    - export PANGEA_AUDIT_CONFIG_ID_1_${ENV}="$(eval echo \$PANGEA_AUDIT_CONFIG_ID_1_${ENV}_${CLOUD})"
    - export PANGEA_AUDIT_CONFIG_ID_2_${ENV}="$(eval echo \$PANGEA_AUDIT_CONFIG_ID_2_${ENV}_${CLOUD})"
    - export PANGEA_AUDIT_CONFIG_ID_3_${ENV}="$(eval echo \$PANGEA_AUDIT_CONFIG_ID_3_${ENV}_${CLOUD})"
    - export PANGEA_REDACT_CONFIG_ID_1_${ENV}="$(eval echo \$PANGEA_REDACT_CONFIG_ID_1_${ENV}_${CLOUD})"
    - export PANGEA_REDACT_CONFIG_ID_2_${ENV}="$(eval echo \$PANGEA_REDACT_CONFIG_ID_2_${ENV}_${CLOUD})"

    - cd packages/pangea-sdk
    - dotnet restore --packages .nuget
    - dotnet build --no-restore --configuration Release

  parallel:
    matrix:
      - CLOUD: [AWS, GCP]
        ENV: ${SERVICE_AUDIT_ENV}
        TEST: ITAuditTest
      - CLOUD: [AWS, GCP]
        ENV: ${SERVICE_AUTHN_ENV}
        TEST: ITAuthNTest
      - CLOUD: [AWS, GCP]
        ENV: ${SERVICE_AUTHZ_ENV}
        TEST: ITAuthZTest
      - CLOUD: [AWS, GCP]
        ENV: ${SERVICE_EMBARGO_ENV}
        TEST: ITEmbargoTest
      - CLOUD: [AWS, GCP]
        ENV: ${SERVICE_DOMAIN_INTEL_ENV}
        TEST: ITDomainIntelTest
      - CLOUD: [AWS, GCP]
        ENV: ${SERVICE_IP_INTEL_ENV}
        TEST: ITIPIntelTest
      - CLOUD: [AWS, GCP]
        ENV: ${SERVICE_URL_INTEL_ENV}
        TEST: ITURLIntelTest
      - CLOUD: [AWS, GCP]
        ENV: ${SERVICE_USER_INTEL_ENV}
        TEST: ITUserIntelTest
      - CLOUD: [AWS, GCP]
        ENV: ${SERVICE_FILE_INTEL_ENV}
        TEST: ITFileIntelTest
      - CLOUD: [AWS, GCP]
        ENV: ${SERVICE_FILE_SCAN_ENV}
        TEST: ITFileScanTest
      - CLOUD: [AWS, GCP]
        ENV: ${SERVICE_REDACT_ENV}
        TEST: ITRedactTest
      - CLOUD: [AWS]
        ENV: ${SERVICE_SANITIZE_ENV}
        TEST: ITSanitizeTest
      - CLOUD: [AWS, GCP]
        ENV: ${SERVICE_VAULT_ENV}
        TEST: ITVaultTest
      - CLOUD: [AWS, GCP]
        ENV: ${SERVICE_SHARE_ENV}
        TEST: ITShareTest
  rules:
    - if: '$CI_COMMIT_BRANCH && $CLOUD == "GCP" && $TEST == "ITFileScanTest"'
      allow_failure: true
    - if: '$CI_COMMIT_BRANCH && $CLOUD == "GCP" && $TEST != "ITFileScanTest"'
      allow_failure: false
    - if: '$CI_COMMIT_BRANCH && $CLOUD != "GCP"'
      allow_failure: false

sdk-lint:
  extends: .sdk-base
  stage: lint
  script:
    - dotnet format --verify-no-changes

sdk-unit-tests:
  extends: .sdk-base
  stage: unit_tests
  script:
    - dotnet test --no-restore --filter SignerTest

sdk-integration-tests:
  extends: .sdk-test-base
  script:
    - dotnet test --no-restore --filter ${TEST}

publish:
  extends: .sdk-base
  stage: publish
  script:
    - bash ../../dev/validate_tag.sh $CI_COMMIT_TAG
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - PACKAGE_VERSION=`cat VERSION`
    - dotnet pack ./PangeaCyber.Net/ -c Release --no-build --nologo -o ./ -p:PackageVersion=$PACKAGE_VERSION
    - cp .secure_files/CodeSigning_CABundle.crt /usr/local/share/ca-certificates
    - update-ca-certificates
    - dotnet nuget sign ./PangeaCyber.Net/bin/Release/Pangea.SDK.$PACKAGE_VERSION.nupkg --timestamper http://timestamp.sectigo.com --certificate-path .secure_files/pangea.pfx -v d
    - dotnet nuget push ./PangeaCyber.Net/bin/Release/Pangea.SDK.$PACKAGE_VERSION.nupkg -s $NUGET_SOURCE -k $NUGET_API_KEY
    - rm -rf .secure_files
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - packages/pangea-sdk/PangeaCyber.Net/bin/Release/Pangea.SDK.*.nupkg
  rules:
    - if: $CI_COMMIT_TAG

stages:
  - lint
  - unit_tests
  - integration_tests
  - examples
  - publish

include:
  - /examples/.examples-ci.yml
